### ISSUE TITLE
help not available unless I have a connection

### ISSUE THREAD

**Issue by crocme10** [byronwasti/movine#14]
Hello,

Thanks for your tool.

I am trying to get help from the CLI, but it says .... connection refused, or no env variable found.

I think I should be able to get a CLI help message without having met the requirements for a connection in the first place.

Thanks

**Comment by byronwasti** [comment]
You are totally right, the current behavior is not correct. I've been meaning to cleanup the CLI tools initialization steps, since they are completely backwards (load config, get connection then parse args, when parse args should be first...)

Hopefully I can fixed up soon!

**Comment by byronwasti** [comment]
Fixed in version `0.9.0`, let me know if there are any other issues.

**Comment by crocme10** [comment]
Thank you, that works great. Thanks for being so responsive!
