### ISSUE TITLE
Publish dockerfile to github packages to be used in Github Actions CI

### ISSUE THREAD

**Issue by ahanoff** [byronwasti/movine#16]
hi @byronwasti  :smile: 
I came to stage when I need to run movine migrations in CI (I'm using Github Actions).
One of the way to do it is actually run Docker Github action (https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action#introduction)

So, I forked movine and tested dockerfile package (https://github.com/ahanoff/movine/packages/503025)
And used that package in planned action https://github.com/ahanoff/movine-action

Actual changes are here: https://github.com/byronwasti/movine/compare/master...ahanoff:master
Ideally I would like to use docker image from your original repository (which can be published on each github release)

Let me know your thoughts :smile: . Thanks

**Comment by byronwasti** [comment]
Hey @ahanoff, thanks for reaching out! If you want to make a PR with the Dockerfile addition I'm happy to merge it and include it with the releases.

**Comment by ahanoff** [comment]
@byronwasti sure, I will create PR tonight. Thanks!
