### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by ahanoff** [byronwasti/movine#8]
As I can see `postgres::NoTls` hard-coded in postgres adaptor, it seems like TLS is not yet supported. Any plans to add?

**Comment by byronwasti** [comment]
Hey, thanks for reaching out. I set up a PR to fix this issue. I haven't gone through and tested things with a generated cert, but given how straightforward the implementation is I'm happy to merge as-is if it looks good to you.

**Comment by ahanoff** [comment]
@byronwasti thanks, that's pretty fast. Let me test it on my db tonight, and I will let you know the outcome.

**Comment by byronwasti** [comment]
TLS support has been merged and should be present in version `0.7.0`. Let me know if you have any issues with that, and thanks for reaching out!
